# This is a basic workflow to help you get started with Actions

name: deploy to github pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir slides
    - name: build slide
      uses: docker://pandoc/core:2.10.1
      with:
        args: -s -t revealjs -o slides/index.html slides.md
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./slides
        enable_jekyll: false
